name: Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel

    steps:
      - name: Install Git & Go
        run: pacman -Syu --needed --noconfirm git go

      - uses: actions/checkout@v3

      - name: Build
        run: go build -v -trimpath -ldflags '-s -w'

      - name: Test
        run: go test -v
